### ISSUE TITLE
Inconvenientes con docker-template.env

### ISSUE THREAD

**Issue by sergiovier** [SIU-Toba/docker-certs#3]
Actualmente, docker.env (copiado de docker-template.env) arroja la siguiente configuración:

```
sergio@devops:~/workspace/docker-certs$ docker-compose config
networks: {}
services:
  certs:
    container_name: certs
    environment:
      CA_DATA: '"/C=AR/O=ROOTCA/OU=SIUTEST/ST=Posadas/CN=ROOTCA/"'
      CA_INT_PWD: '''cambiametambien'''
      CA_PWD: '''cambiame'''
      DOCKER_NAME: certs
      LISTA_CLIENTES: cliente1 cliente2 cliente3
      LISTA_SERVER: dominio dominio2 dominio3
    image: siutoba/docker-certs
    network_mode: bridge
    volumes:
    - ~/workspace/docker-certs/docker-data/certs/certificados:/CAs/intermediate:rw
    - ~/workspace/docker-certs/docker-data/certs/root:/CAs/rootCA:rw
version: '2.0'
volumes: {}
```

Notar que las variables definidas en `docker.env`  no pueden tener comillas ya que se trasladan escapadas... bash entiendo permite definir variables tipo string sin necesidad de comillas. 

Por otro lado, si queremos defininir CRT_DATA, no me queda claro como crearla... ya que [acá](https://github.com/SIU-Toba/docker-certs/blob/master/bin/crea_client_cert.sh#L16) y [acá](https://github.com/SIU-Toba/docker-certs/blob/master/bin/crea_server_cert.sh#L16) se está armando una por cada certificado cliente/servidor, con el CN respectivo. Podríamos hacer que solo la parte `C`, `OU`, `ST` sean personalizables y `CN` lo arme al momento de usar el CRT_DATA.
